version: '2.1'
services:
  localstack:
    image: localstack/localstack
    ports:
      - 4567-4583:4567-4583
      - 8080:8080
    environment:
      - DEFAULT_REGION=ap-northeast-1
      - HOSTNAME=localstack.test
      - DATA_DIR=/tmp/localstack
    privileged: true
